/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedFundsRouteImport } from './routes/(authenticated)/funds'
import { Route as authenticatedCategoriesRouteImport } from './routes/(authenticated)/categories'

const authenticatedIndexLazyRouteImport = createFileRoute('/(authenticated)/')()

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexLazyRoute = authenticatedIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(authenticated)/index.lazy').then((d) => d.Route),
  )
const authenticatedFundsRoute = authenticatedFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedCategoriesRoute = authenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => authenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/categories': typeof authenticatedCategoriesRoute
  '/funds': typeof authenticatedFundsRoute
  '/': typeof authenticatedIndexLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/categories': typeof authenticatedCategoriesRoute
  '/funds': typeof authenticatedFundsRoute
  '/': typeof authenticatedIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/(authenticated)/categories': typeof authenticatedCategoriesRoute
  '/(authenticated)/funds': typeof authenticatedFundsRoute
  '/(authenticated)/': typeof authenticatedIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/categories' | '/funds' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/categories' | '/funds' | '/'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/login'
    | '/register'
    | '/(authenticated)/categories'
    | '/(authenticated)/funds'
    | '/(authenticated)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexLazyRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/funds': {
      id: '/(authenticated)/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof authenticatedFundsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/categories': {
      id: '/(authenticated)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof authenticatedCategoriesRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedCategoriesRoute: typeof authenticatedCategoriesRoute
  authenticatedFundsRoute: typeof authenticatedFundsRoute
  authenticatedIndexLazyRoute: typeof authenticatedIndexLazyRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedCategoriesRoute: authenticatedCategoriesRoute,
  authenticatedFundsRoute: authenticatedFundsRoute,
  authenticatedIndexLazyRoute: authenticatedIndexLazyRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
